### ISSUE TITLE
Logs showing all working, but nothing gets applied

### ISSUE THREAD

**Issue by JianGuo222** [utilitywarehouse/kube-applier#18]
Hi there,

here are the logs I'm getting:
![image](https://user-images.githubusercontent.com/4733589/39169132-e558adb8-47d9-11e8-92cc-123bf98cb1ba.png)

there are no clear errors in the log above, but my latest yaml file changes have not been applied.

the file structure in my repo is
![image](https://user-images.githubusercontent.com/4733589/39169337-cb4b43ee-47da-11e8-8405-4a95c521ca0e.png)

dell-hymes is one of my namespaces

I can verify the actual deploy yaml files have been updated in the container by bashing in:
`kubectl exec -it <kube-applie-pod-name> --container kube-applier -- /bin/sh`
then the folder is here
`cd /k8s/git_source/kubernetes/`

and running kubectl apply command manually inside the container works fine.

can someone help me?

thanks
J

**Comment by JianGuo222** [comment]
btw, I'm using 
`image: "utilitywarehouse/kube-applier:1.8.8-2"`

**Comment by george-angel** [comment]
Hey @JianGuo222 I'm sorry for not replying, somehow missed this one, we have since added logging levels, is this still an issue for you? If so, do you mind trying one of the later versions with info level logging?

Thanks.

**Comment by george-angel** [comment]
Closing, let me know if this is still an issue.
