### ISSUE TITLE
Trigger a rolling update of the Deployment

### ISSUE THREAD

**Issue by dawidmalina** [utilitywarehouse/kube-applier#29]
It would be nice to have ability to trigger a rolling update of the Deployment when it’s dependent ConfigMaps and Secrets are updated.

Similar what was described here: https://boxboat.com/2018/07/05/gitops-kubernetes-rolling-update-configmap-secret-change/

**Comment by dawidmalina** [comment]
There are some toole which help on this:
- https://github.com/xing/kubernetes-deployment-restart-controller
- https://github.com/stakater/reloader

But I would love to see this implemented in kube-applier :)

**Comment by george-angel** [comment]
Hey @dawidmalina sorry for such long silence, need to adjust my notification settings it seems.

We have added Kustomize (https://github.com/kubernetes-sigs/kustomize) functionality in kube-applier, which facilitates exactly that.

This works for us, we are unlikely to implement rolling updates separate in KA.
