### ISSUE TITLE
Kustomize errors are swallowed

### ISSUE THREAD

**Issue by davidsbond** [utilitywarehouse/kube-applier#98]
Ran 2.3.9 in dev to test out upgrading, noticed that the apply command is swallowing errors returned by kustomize

When trying to apply, this command is ran:

```
kustomize build dev-aws/partner-platform-api | kubectl apply --server-dry-run=true -f - -n partner-platform-api
```

This was returning an error along the lines of `no objects to apply`, which is confusing as there are manifests in that namespace. When I ran `kustomize build dev-aws/partner-platform-api` locally, there was an error in the manifests due to a breaking change in kustomize where config/secret generators expect `envs` as a string array instead of `env`.

Seems like piping into `kubectl` like this swallows that error message.

**Comment by george-angel** [comment]
fixed in: https://github.com/utilitywarehouse/kube-applier/pull/99
